### ISSUE TITLE
Unhandled exception:  Suspicious path detected

### ISSUE THREAD

**Issue by ZonD80** [ChiChou/bagbak#50]
**Describe the bug**
There is unhandled exception that fails dumping process of extensions, leads that app can't be dumped.

**To Reproduce**
bagbak -z --override com.Yooshr.Infltr

https://apps.apple.com/ru/app/infltr-infinite-filters/id935623257?l=en

**Expected behavior**
Guess skipping of system extensions, as looks like BTAvrcp is related to bluetooth daemon

**Screenshots**
<img width="873" alt="image" src="https://user-images.githubusercontent.com/273057/88580830-e8377400-d054-11ea-8207-f8af826ae0b4.png">

**Desktop (please complete the following information):**
 - OS: Any
 - nodejs: Any
 - frida-node: Any
 - frida on device version Any
 - 12.4.7 checkra1n
 - com.Yooshr.Infltr

**Comment by ChiChou** [comment]
This is a strange test case that triggered an assertion error. All paths are expected to be inside the app bundle, but there is a `/usr/sbin/BTAvrcp` in this particular app. I'll investigate this

**Comment by ChiChou** [comment]
Before I fix this problem by migrating to `mremap_encrypted` and on-device packaging, I recommend [FlexDecrypt](https://github.com/JohnCoates/flexdecrypt). The problem is that it can only decrypt executables one by one, not to mention generating a `ipa` archive.

I made a VSCode plugin that provides friendly GUI and wraps FlexDecrypt command to pull decrypted ipa from jailbroken iDevice:

https://github.com/ChiChou/vscode-frida/raw/593583cd257394eeb67840d2e3b0e7860887c993/resources/doc/flexdecrypt.png

Please check it out here https://github.com/ChiChou/vscode-frida

**Comment by ZonD80** [comment]
Hi. Any news?

**Comment by ChiChou** [comment]
@ZonD80 it should be working now

**Comment by ZonD80** [comment]
Thank you! Will test on Monday
